services:
  web:
    build: .
    container_name: lead-collector
    volumes:
      - .:/usr/src/app
      - ./logs/:/usr/src/app/logs/
      - ./lead-collector-static/:/usr/src/app/lead-collector-static/
    ports:
      - "8000:8000"
    env_file:
      - .env
